name: SonarCloud Analysis with Quality Gate

on:
  push:
    branches:
      - main
      - maitreyrbhatt-patch-1
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # REQUIRED for branch & PR analysis

      - name: show cloned repo
        run: |
          pwd
          ls -al
          dir

      # SonarCloud scan (ALL properties inline)
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=sonarcloudqualitycheck
            -Dsonar.projectKey=jitu234392_sonarcloud
            -Dsonar.projectName=sonarcloud-demo
            -Dsonar.sources=.
            -Dsonar.exclusions=**/tests/**,**/docs/**,**/vendor/**,**/*.md
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.qualitygate.wait=true
            -Dsonar.qualitygate.timeout=300
